let shopItemsData = [
    {
      id: "jfhgbvnscs",
      name: "Casual Shirt",
      price: 45,
      desc: "sports shirt .. other colors are also available...",
      img: "images/img-10.jpg",
    },
    {
      id: "ioytrhndcv",
      name: "Office Shirt",
      price: 100,
      desc: "Don't miss the beautiful shirts...",
      img: "images/img-9.jpg",
    },
    {
      id: "wuefbncxbsn",
      name: "Long Dress",
      price: 300,
      desc: "available in other colors...",
      img: "images/img-5.jpg",
    },
    {
      id: "thyfhcbcv",
      name: "Mens Shirt",
      price: 35,
      desc: "Don't miss the beautiful suits...",
      img: "images/img-8.jpg",
    },
    {
      id: "a",
      name: "Long Dress",
      price: 45,
      desc: "sports shirt .. other colors are also available...",
      img: "images/img-6.jpg",
    },
    {
      id: "b",
      name: "T-Shirt",
      price: 100,
      desc: "Don't miss the most preferred t-shirts....",
      img: "images/img-7.jpg",
    },
    {
      id: "c",
      name: "Shirt",
      price: 80,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-1.jpg",
    },
    {
      id: "d",
      name: "Mens Suit",
      price: 300,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-2.jpg",
    },
    {
      id: "e",
      name: "Casual Shirt",
      price: 200,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-4.jpg",
    },
    {
      id: "f",
      name: "Office Shirt",
      price: 100,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-11.jpg",
    },
    {
      id: "g",
      name: "T Shirt",
      price: 60,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-12.jpg",
    },
    {
      id: "h",
      name: "Mens Suit",
      price: 85,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-13.jpg",
    },
  ];